package br.org.asipeca.assist.model;
// Generated 20 de out de 2018 18:44:07 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AssiSituSaud generated by hbm2java
 */
@Entity
@Table(name = "assi_situ_saud", catalog = "asipeca", uniqueConstraints = @UniqueConstraint(columnNames = { "assi_id",
		"situ_saud_id" }))
public class AssiSituSaud implements java.io.Serializable {

	private static final long serialVersionUID = 3716390918835390107L;
	private Long assiSituSaudId;
	private Assi assi;
	private SituSaud situSaud;
	private Date criaEm;
	private Long criaPo;
	private Date alteEm;
	private Long altePo;

	public AssiSituSaud() {
	}

	public AssiSituSaud(Assi assi, SituSaud situSaud) {
		this.assi = assi;
		this.situSaud = situSaud;
	}

	public AssiSituSaud(Assi assi, SituSaud situSaud, Date criaEm, Long criaPo, Date alteEm, Long altePo) {
		this.assi = assi;
		this.situSaud = situSaud;
		this.criaEm = criaEm;
		this.criaPo = criaPo;
		this.alteEm = alteEm;
		this.altePo = altePo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assi_situ_saud_id", unique = true, nullable = false)
	public Long getAssiSituSaudId() {
		return this.assiSituSaudId;
	}

	public void setAssiSituSaudId(Long assiSituSaudId) {
		this.assiSituSaudId = assiSituSaudId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assi_id", nullable = false)
	public Assi getAssi() {
		return this.assi;
	}

	public void setAssi(Assi assi) {
		this.assi = assi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situ_saud_id", nullable = false)
	public SituSaud getSituSaud() {
		return this.situSaud;
	}

	public void setSituSaud(SituSaud situSaud) {
		this.situSaud = situSaud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cria_em", length = 26)
	public Date getCriaEm() {
		return this.criaEm;
	}

	public void setCriaEm(Date criaEm) {
		this.criaEm = criaEm;
	}

	@Column(name = "cria_po")
	public Long getCriaPo() {
		return this.criaPo;
	}

	public void setCriaPo(Long criaPo) {
		this.criaPo = criaPo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "alte_em", length = 26)
	public Date getAlteEm() {
		return this.alteEm;
	}

	public void setAlteEm(Date alteEm) {
		this.alteEm = alteEm;
	}

	@Column(name = "alte_po")
	public Long getAltePo() {
		return this.altePo;
	}

	public void setAltePo(Long altePo) {
		this.altePo = altePo;
	}

}
