package br.org.asipeca.assist.model;
// Generated 20 de out de 2018 18:44:07 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AssiIdenInte generated by hbm2java
 */
@Entity
@Table(name = "assi_iden_inte", catalog = "asipeca", uniqueConstraints = @UniqueConstraint(columnNames = { "assi_id",
		"iden_inte_id" }))
public class AssiIdenInte implements java.io.Serializable {

	private static final long serialVersionUID = 6874036809580929646L;
	private Long assiIdenInteId;
	private Assi assi;
	private IdenInte idenInte;
	private Date criaEm;
	private Long criaPo;
	private Date alteEm;
	private Long altePo;

	public AssiIdenInte() {
	}

	public AssiIdenInte(Assi assi, IdenInte idenInte) {
		this.assi = assi;
		this.idenInte = idenInte;
	}

	public AssiIdenInte(Assi assi, IdenInte idenInte, Date criaEm, Long criaPo, Date alteEm, Long altePo) {
		this.assi = assi;
		this.idenInte = idenInte;
		this.criaEm = criaEm;
		this.criaPo = criaPo;
		this.alteEm = alteEm;
		this.altePo = altePo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assi_iden_inte_id", unique = true, nullable = false)
	public Long getAssiIdenInteId() {
		return this.assiIdenInteId;
	}

	public void setAssiIdenInteId(Long assiIdenInteId) {
		this.assiIdenInteId = assiIdenInteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assi_id", nullable = false)
	public Assi getAssi() {
		return this.assi;
	}

	public void setAssi(Assi assi) {
		this.assi = assi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iden_inte_id", nullable = false)
	public IdenInte getIdenInte() {
		return this.idenInte;
	}

	public void setIdenInte(IdenInte idenInte) {
		this.idenInte = idenInte;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cria_em", length = 26)
	public Date getCriaEm() {
		return this.criaEm;
	}

	public void setCriaEm(Date criaEm) {
		this.criaEm = criaEm;
	}

	@Column(name = "cria_po")
	public Long getCriaPo() {
		return this.criaPo;
	}

	public void setCriaPo(Long criaPo) {
		this.criaPo = criaPo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "alte_em", length = 26)
	public Date getAlteEm() {
		return this.alteEm;
	}

	public void setAlteEm(Date alteEm) {
		this.alteEm = alteEm;
	}

	@Column(name = "alte_po")
	public Long getAltePo() {
		return this.altePo;
	}

	public void setAltePo(Long altePo) {
		this.altePo = altePo;
	}

}
