package br.org.asipeca.assist.model;
// Generated 20 de out de 2018 18:44:07 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Assi generated by hbm2java
 */
@Entity
@Table(name = "assi", catalog = "asipeca", uniqueConstraints = @UniqueConstraint(columnNames = "cpf"))
public class Assi implements java.io.Serializable {

	private static final long serialVersionUID = -1597716660885975677L;
	private Long assiId;
	private Esco esco;
	private FaseEsta faseEsta;
	private RendMens rendMens;
	private SituMora situMora;
	private SituOcup situOcup;
	private SituSaud situSaud;
	private String nome;
	private Date nasc;
	private String gene;
	private String tipoCada;
	private String rg;
	private String nis;
	private String sus;
	private Long cpf;
	private Boolean numeMembFami;
	private Date dataDiag;
	private Boolean famiPart;
	private Date criaEm;
	private Long criaPo;
	private Date alteEm;
	private Long altePo;
	private Set<AssiVincRedeApoi> assiVincRedeApois = new HashSet<AssiVincRedeApoi>(0);
	private Set<AssiIdenInte> assiIdenIntes = new HashSet<AssiIdenInte>(0);
	private Set<AssiInteSaud> assiInteSauds = new HashSet<AssiInteSaud>(0);
	private Set<AssiPatoAsso> assiPatoAssos = new HashSet<AssiPatoAsso>(0);
	private Set<AssiHabiSaud> assiHabiSauds = new HashSet<AssiHabiSaud>(0);
	private Set<AssiIdenAten> assiIdenAtens = new HashSet<AssiIdenAten>(0);
	private Set<AssiSituSaud> assiSituSauds = new HashSet<AssiSituSaud>(0);
	private Set<AssiHistFami> assiHistFamis = new HashSet<AssiHistFami>(0);
	private Set<AssiTipoCanc> assiTipoCancs = new HashSet<AssiTipoCanc>(0);

	public Assi() {
	}

	public Assi(String nome) {
		this.nome = nome;
	}

	public Assi(Esco esco, FaseEsta faseEsta, RendMens rendMens, SituMora situMora, SituOcup situOcup,
			SituSaud situSaud, String nome, Date nasc, String gene, String tipoCada, String rg, String nis, String sus,
			Long cpf, Boolean numeMembFami, Date dataDiag, Boolean famiPart, Date criaEm, Long criaPo, Date alteEm,
			Long altePo, Set<AssiVincRedeApoi> assiVincRedeApois, Set<AssiIdenInte> assiIdenIntes,
			Set<AssiInteSaud> assiInteSauds, Set<AssiPatoAsso> assiPatoAssos, Set<AssiHabiSaud> assiHabiSauds,
			Set<AssiIdenAten> assiIdenAtens, Set<AssiSituSaud> assiSituSauds, Set<AssiHistFami> assiHistFamis,
			Set<AssiTipoCanc> assiTipoCancs) {
		this.esco = esco;
		this.faseEsta = faseEsta;
		this.rendMens = rendMens;
		this.situMora = situMora;
		this.situOcup = situOcup;
		this.situSaud = situSaud;
		this.nome = nome;
		this.nasc = nasc;
		this.gene = gene;
		this.tipoCada = tipoCada;
		this.rg = rg;
		this.nis = nis;
		this.sus = sus;
		this.cpf = cpf;
		this.numeMembFami = numeMembFami;
		this.dataDiag = dataDiag;
		this.famiPart = famiPart;
		this.criaEm = criaEm;
		this.criaPo = criaPo;
		this.alteEm = alteEm;
		this.altePo = altePo;
		this.assiVincRedeApois = assiVincRedeApois;
		this.assiIdenIntes = assiIdenIntes;
		this.assiInteSauds = assiInteSauds;
		this.assiPatoAssos = assiPatoAssos;
		this.assiHabiSauds = assiHabiSauds;
		this.assiIdenAtens = assiIdenAtens;
		this.assiSituSauds = assiSituSauds;
		this.assiHistFamis = assiHistFamis;
		this.assiTipoCancs = assiTipoCancs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assi_id", unique = true, nullable = false)
	public Long getAssiId() {
		return this.assiId;
	}

	public void setAssiId(Long assiId) {
		this.assiId = assiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "esco_id")
	public Esco getEsco() {
		return this.esco;
	}

	public void setEsco(Esco esco) {
		this.esco = esco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fase_esta_id")
	public FaseEsta getFaseEsta() {
		return this.faseEsta;
	}

	public void setFaseEsta(FaseEsta faseEsta) {
		this.faseEsta = faseEsta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rend_mens_id")
	public RendMens getRendMens() {
		return this.rendMens;
	}

	public void setRendMens(RendMens rendMens) {
		this.rendMens = rendMens;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situ_mora_id")
	public SituMora getSituMora() {
		return this.situMora;
	}

	public void setSituMora(SituMora situMora) {
		this.situMora = situMora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situ_ocup_id")
	public SituOcup getSituOcup() {
		return this.situOcup;
	}

	public void setSituOcup(SituOcup situOcup) {
		this.situOcup = situOcup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situ_saud_id")
	public SituSaud getSituSaud() {
		return this.situSaud;
	}

	public void setSituSaud(SituSaud situSaud) {
		this.situSaud = situSaud;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nasc", length = 10)
	public Date getNasc() {
		return this.nasc;
	}

	public void setNasc(Date nasc) {
		this.nasc = nasc;
	}

	@Column(name = "gene", length = 9)
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	@Column(name = "tipo_cada", length = 21)
	public String getTipoCada() {
		return this.tipoCada;
	}

	public void setTipoCada(String tipoCada) {
		this.tipoCada = tipoCada;
	}

	@Column(name = "rg", length = 9)
	public String getRg() {
		return this.rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@Column(name = "nis", length = 50)
	public String getNis() {
		return this.nis;
	}

	public void setNis(String nis) {
		this.nis = nis;
	}

	@Column(name = "sus", length = 30)
	public String getSus() {
		return this.sus;
	}

	public void setSus(String sus) {
		this.sus = sus;
	}

	@Column(name = "cpf", unique = true)
	public Long getCpf() {
		return this.cpf;
	}

	public void setCpf(Long cpf) {
		this.cpf = cpf;
	}

	@Column(name = "nume_memb_fami")
	public Boolean getNumeMembFami() {
		return this.numeMembFami;
	}

	public void setNumeMembFami(Boolean numeMembFami) {
		this.numeMembFami = numeMembFami;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_diag", length = 26)
	public Date getDataDiag() {
		return this.dataDiag;
	}

	public void setDataDiag(Date dataDiag) {
		this.dataDiag = dataDiag;
	}

	@Column(name = "fami_part")
	public Boolean getFamiPart() {
		return this.famiPart;
	}

	public void setFamiPart(Boolean famiPart) {
		this.famiPart = famiPart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cria_em", length = 26)
	public Date getCriaEm() {
		return this.criaEm;
	}

	public void setCriaEm(Date criaEm) {
		this.criaEm = criaEm;
	}

	@Column(name = "cria_po")
	public Long getCriaPo() {
		return this.criaPo;
	}

	public void setCriaPo(Long criaPo) {
		this.criaPo = criaPo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "alte_em", length = 26)
	public Date getAlteEm() {
		return this.alteEm;
	}

	public void setAlteEm(Date alteEm) {
		this.alteEm = alteEm;
	}

	@Column(name = "alte_po")
	public Long getAltePo() {
		return this.altePo;
	}

	public void setAltePo(Long altePo) {
		this.altePo = altePo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiVincRedeApoi> getAssiVincRedeApois() {
		return this.assiVincRedeApois;
	}

	public void setAssiVincRedeApois(Set<AssiVincRedeApoi> assiVincRedeApois) {
		this.assiVincRedeApois = assiVincRedeApois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiIdenInte> getAssiIdenIntes() {
		return this.assiIdenIntes;
	}

	public void setAssiIdenIntes(Set<AssiIdenInte> assiIdenIntes) {
		this.assiIdenIntes = assiIdenIntes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiInteSaud> getAssiInteSauds() {
		return this.assiInteSauds;
	}

	public void setAssiInteSauds(Set<AssiInteSaud> assiInteSauds) {
		this.assiInteSauds = assiInteSauds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiPatoAsso> getAssiPatoAssos() {
		return this.assiPatoAssos;
	}

	public void setAssiPatoAssos(Set<AssiPatoAsso> assiPatoAssos) {
		this.assiPatoAssos = assiPatoAssos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiHabiSaud> getAssiHabiSauds() {
		return this.assiHabiSauds;
	}

	public void setAssiHabiSauds(Set<AssiHabiSaud> assiHabiSauds) {
		this.assiHabiSauds = assiHabiSauds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiIdenAten> getAssiIdenAtens() {
		return this.assiIdenAtens;
	}

	public void setAssiIdenAtens(Set<AssiIdenAten> assiIdenAtens) {
		this.assiIdenAtens = assiIdenAtens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiSituSaud> getAssiSituSauds() {
		return this.assiSituSauds;
	}

	public void setAssiSituSauds(Set<AssiSituSaud> assiSituSauds) {
		this.assiSituSauds = assiSituSauds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiHistFami> getAssiHistFamis() {
		return this.assiHistFamis;
	}

	public void setAssiHistFamis(Set<AssiHistFami> assiHistFamis) {
		this.assiHistFamis = assiHistFamis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assi")
	public Set<AssiTipoCanc> getAssiTipoCancs() {
		return this.assiTipoCancs;
	}

	public void setAssiTipoCancs(Set<AssiTipoCanc> assiTipoCancs) {
		this.assiTipoCancs = assiTipoCancs;
	}

}
