package br.org.asipeca.assist.model;
// Generated 20 de out de 2018 18:44:07 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Idad generated by hbm2java
 */
@Entity
@Table(name = "idad", catalog = "asipeca")
public class Idad implements java.io.Serializable {

	private static final long serialVersionUID = 8082345342486139284L;
	private Long idadId;
	private String dscr;
	private Short limiInfe;
	private Short limiSupe;

	public Idad() {
	}

	public Idad(String dscr, Short limiInfe, Short limiSupe) {
		this.dscr = dscr;
		this.limiInfe = limiInfe;
		this.limiSupe = limiSupe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idad_id", unique = true, nullable = false)
	public Long getIdadId() {
		return this.idadId;
	}

	public void setIdadId(Long idadId) {
		this.idadId = idadId;
	}

	@Column(name = "dscr", length = 30)
	public String getDscr() {
		return this.dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	@Column(name = "limi_infe")
	public Short getLimiInfe() {
		return this.limiInfe;
	}

	public void setLimiInfe(Short limiInfe) {
		this.limiInfe = limiInfe;
	}

	@Column(name = "limi_supe")
	public Short getLimiSupe() {
		return this.limiSupe;
	}

	public void setLimiSupe(Short limiSupe) {
		this.limiSupe = limiSupe;
	}

}
