package br.org.asipeca.assist.model;
// Generated 20 de out de 2018 18:44:07 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NumeMembFami generated by hbm2java
 */
@Entity
@Table(name = "nume_memb_fami", catalog = "asipeca")
public class NumeMembFami implements java.io.Serializable {

	private Long numeMembFamiId;
	private String dscr;
	private Short limiInfe;
	private Short limiSupe;

	public NumeMembFami() {
	}

	public NumeMembFami(String dscr, Short limiInfe, Short limiSupe) {
		this.dscr = dscr;
		this.limiInfe = limiInfe;
		this.limiSupe = limiSupe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nume_memb_fami_id", unique = true, nullable = false)
	public Long getNumeMembFamiId() {
		return this.numeMembFamiId;
	}

	public void setNumeMembFamiId(Long numeMembFamiId) {
		this.numeMembFamiId = numeMembFamiId;
	}

	@Column(name = "dscr", length = 30)
	public String getDscr() {
		return this.dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	@Column(name = "limi_infe")
	public Short getLimiInfe() {
		return this.limiInfe;
	}

	public void setLimiInfe(Short limiInfe) {
		this.limiInfe = limiInfe;
	}

	@Column(name = "limi_supe")
	public Short getLimiSupe() {
		return this.limiSupe;
	}

	public void setLimiSupe(Short limiSupe) {
		this.limiSupe = limiSupe;
	}

}
