package br.org.asipeca.assist.model;
// Generated 20 de out de 2018 18:44:07 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TempDiag generated by hbm2java
 */
@Entity
@Table(name = "temp_diag", catalog = "asipeca")
public class TempDiag implements java.io.Serializable {

	private static final long serialVersionUID = 8607187054304027438L;
	private Long tempDiagId;
	private String dscr;
	private Short limiInfe;
	private Short limiSupe;
	private Date criaEm;
	private Long criaPo;
	private Date alteEm;
	private Long altePo;

	public TempDiag() {
	}

	public TempDiag(String dscr, Short limiInfe, Short limiSupe, Date criaEm, Long criaPo, Date alteEm, Long altePo) {
		this.dscr = dscr;
		this.limiInfe = limiInfe;
		this.limiSupe = limiSupe;
		this.criaEm = criaEm;
		this.criaPo = criaPo;
		this.alteEm = alteEm;
		this.altePo = altePo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "temp_diag_id", unique = true, nullable = false)
	public Long getTempDiagId() {
		return this.tempDiagId;
	}

	public void setTempDiagId(Long tempDiagId) {
		this.tempDiagId = tempDiagId;
	}

	@Column(name = "dscr", length = 30)
	public String getDscr() {
		return this.dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	@Column(name = "limi_infe")
	public Short getLimiInfe() {
		return this.limiInfe;
	}

	public void setLimiInfe(Short limiInfe) {
		this.limiInfe = limiInfe;
	}

	@Column(name = "limi_supe")
	public Short getLimiSupe() {
		return this.limiSupe;
	}

	public void setLimiSupe(Short limiSupe) {
		this.limiSupe = limiSupe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cria_em", length = 26)
	public Date getCriaEm() {
		return this.criaEm;
	}

	public void setCriaEm(Date criaEm) {
		this.criaEm = criaEm;
	}

	@Column(name = "cria_po")
	public Long getCriaPo() {
		return this.criaPo;
	}

	public void setCriaPo(Long criaPo) {
		this.criaPo = criaPo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "alte_em", length = 26)
	public Date getAlteEm() {
		return this.alteEm;
	}

	public void setAlteEm(Date alteEm) {
		this.alteEm = alteEm;
	}

	@Column(name = "alte_po")
	public Long getAltePo() {
		return this.altePo;
	}

	public void setAltePo(Long altePo) {
		this.altePo = altePo;
	}

}
